import { createClient } from "@supabase/supabase-js";

// The map's data, current rather than remembered.
//
// This used to be public/mines.json, a file generated by hand once and then
// left. The mines in it do not move, so that was fine for the geography and
// wrong for the one field that changes: the live job count. The job finder runs
// every night and the file did not, so by the time anyone looked, Mount Isa was
// advertising seventeen opportunities and had ten.
//
// Every drift was in the same direction, because a listing going stale removes
// one and nothing ever added one back. The map was reliably promising more work
// than existed, which is the worst way for a number like this to be wrong.
//
// Served from here instead, cached for an hour. The counts only move once a
// night, so an hour is fresh by any measure that matters and Supabase sees
// twenty four requests a day rather than one per visitor.

export const runtime = "nodejs";

// Deliberately NOT `dynamic = "force-static"`, which is how a GET handler opts
// into Next's cache in this version. That prerenders at build time, so the job
// counts would freeze at whatever they were the day of the deploy: the same bug
// as the hand generated file, moved somewhere harder to see.
//
// The route runs per request and the CDN does the caching instead, through the
// Cache-Control header at the bottom. Same saving, and the clock starts when
// somebody asks rather than when the site was last built.

type Row = {
  id: string; name: string; state: string; slug: string;
  latitude: number | null; longitude: number | null;
  status: string; commodity: string[] | null;
};

// The same compact keys the map already reads, so nothing downstream changes.
// Short names because this is five hundred records going over the wire to a
// phone, often on site reception.
type Mine = {
  n: string; s: string; la: number; lo: number;
  st: string; c: string; j?: number; u: string;
};

const DIRECTORY = "https://mines.frontlinetalentgroup.com.au";

export async function GET() {
  // Service role, deliberately. The mines and job_listings tables are not
  // readable by the public key, which is correct and worth keeping: this reads
  // them on the server and hands back only what the map draws.
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    return Response.json({ error: "Mine data is not configured here." }, { status: 503 });
  }

  const db = createClient(url, key, { auth: { persistSession: false } });

  const { data: mines, error } = await db
    .from("mines")
    .select("id, name, state, slug, latitude, longitude, status, commodity")
    .limit(5000);
  // Said out loud rather than returning an empty map, which looks identical to
  // a country with no mines in it.
  if (error) {
    return Response.json({ error: `Could not read the mines: ${error.message}` }, { status: 502 });
  }

  // Counted here rather than asked of the database per mine: it is one read of
  // a few thousand short rows against five hundred round trips.
  const counts = new Map<string, number>();
  const { data: jobs, error: jobErr } = await db
    .from("job_listings")
    .select("mine_id")
    .eq("active", true)
    .limit(20000);
  // A missing job count is survivable and a missing map is not, so this failure
  // costs the gold markers and nothing else.
  if (!jobErr) {
    for (const j of jobs ?? []) {
      const id = (j as { mine_id: string }).mine_id;
      counts.set(id, (counts.get(id) ?? 0) + 1);
    }
  }

  const out: Mine[] = [];
  for (const m of (mines ?? []) as Row[]) {
    // No coordinates means nothing to draw.
    if (m.latitude == null || m.longitude == null) continue;
    const j = counts.get(m.id) ?? 0;
    out.push({
      n: m.name, s: m.state, la: m.latitude, lo: m.longitude,
      st: m.status, c: (m.commodity ?? []).join(", "),
      // Absent rather than zero, which is what the map already expects and what
      // keeps the payload small for the four hundred sites with no work on.
      ...(j > 0 ? { j } : {}),
      u: `${DIRECTORY}/mines/${m.state}/${m.slug}`,
    });
  }

  return Response.json(out, {
    headers: {
      // Stale-while-revalidate so a visitor never waits on the refresh: they
      // get the previous answer instantly and the next one gets the new count.
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
